export const LOGIN_METAMASK = "LOGIN_METAMASK";
export const AUTH_WINARY = "AUTH_WINARY";

export const SHOW_ALERT = "SHOW_ALERT";

export const CLOSE_ALERT = "CLOSE_ALERT";
export const SET_FILTER = "SET_FILTER";
export const GET_FILTER = "GET_FILTER";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";
