export const GET_REDEEMS = "GET_REDEEMS";
export const GET_WINARYS = "GET_WINARYS";
export const GET_PROVINCES = "GET_PROVINCES";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const AUTH_WINARY = "AUTH_WINARY";

export const SHOW_ALERT = "SHOW_ALERT";

export const CLOSE_ALERT = "CLOSE_ALERT";
export const SET_FILTER = "SET_FILTER";
export const GET_FILTER = "GET_FILTER";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";
export const EXPAND_NOTIFICATION = "EXPAND_NOTIFICATION";
export const COLLAPSE_NOTIFICATION = "COLLAPSE_NOTIFICATION";
