import Table from "@/components/Table";
import React from "react";

const redeems = () => {
  const columnas = [
    {
      title: "",
      field: "acciones",
    },
    {
      title: "Artista",
      field: "artista",
    },
    {
      title: "País de origen",
      field: "pais",
    },
    {
      title: "Géneros",
      field: "genero",
    },
    {
      title: "Ventas estimadas en millones",
      field: "ventas",
      type: "numeric",
    },
    {
      title: "Status",
      field: "status",
    },
  ];

  const data = [
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
    {
      artista: "Charly Garcia",
      pais: "Argentina",
      genero: "Rock",
      ventas: 100,
      status: "success",
    },
    {
      artista: "The Beatles",
      pais: "England",
      genero: "Rock",
      ventas: 1000,
      status: "pending",
    },
    {
      artista: "Fito Paez",
      pais: "Argentina",
      genero: "Rock",
      ventas: 500,
      status: "rejected",
    },
  ];
  return (
    <div className="mx-auto p-10">
      <Table data={data} columnas={columnas} />
    </div>
  );
};

export default redeems;
